import React,{useState} from 'react'
import Sidebar from '../Sidebar/Sidebar'
import NavbarMenu from '../NavbarMenu/NavbarMenu'
import { Button, Col, Container , Row ,Form ,Tooltip,OverlayTrigger} from 'react-bootstrap'
import CreatableSelect from 'react-select/creatable';
import { ActionMeta, OnChangeValue } from 'react-select';
import { ToastContainer, toast } from 'react-toastify';

import { Link } from 'react-router-dom';
const FilterStudent = () => {
    const [showskill, setshowskill]=useState(false);
    const handleShowskill = ()=> setshowskill(!showskill)
    const [showdropdown, setshowdropdown] =useState(false);
 const handleShowdropdown = () => 
   setshowdropdown(!showdropdown)
   const [show4, setShow4] = useState(false);
   const handleClose4 = () => setShow4(false);
   const handleShow4 = () => setShow4(true);
   const [show3, setShow3] = useState(false);
   const handleClose3 = () => setShow3(false);
   const handleShow3 = () => setShow3(true);
   const options = [
    {label:"Virtual/Telephonic- Any mutually decided time. (this week/next week)", value:"Virtual/Telephonic- Any mutually decided time. (this week/next week)"},
    {label:"F2F- Any mutually decided time (this week/next week)", value:"F2F- Any mutually decided time (this week/next week)"},
    {label:"Create", value:""}
  ]
    // const options=[
    //     {label:"Negotiable", value:"Negotiable"},
    //     {label:"Non-Negotiable", value:"Non-Negotiable"},
    // ]
    // const option1=[
    //     {label:"Yes", value:"Yes"},
    //     {label:"No", value:"No"},
    // ]
    const   handleChange = (
        newValue: OnChangeValue<ColourOption, false>,
        actionMeta: ActionMeta<ColourOption>
      ) => {
        console.group('Value Changed');
        console.log(newValue);
        console.log(`action: ${actionMeta.action}`);
        console.groupEnd();
      };
    const   handleInputChange = (inputValue: any, actionMeta: any) => {
        console.group('Input Changed');
        console.log(inputValue);
        console.log(`action: ${actionMeta.action}`);
        console.groupEnd();
      };
  return (
    <div>
        <Sidebar />
        <NavbarMenu />
        <div className='people'>
          <h4 className='mt-5 text-muted text-center mt-5'>Filter Candidates List</h4>
   
        <Container className='search-contact'>
            
            <Form>
        <Row>
            <Col xs={12}>
              <Form.Group className='mt-2 mb-2'>
                <Form.Label className='fw-bold'>Candidate ID </Form.Label>
                <Form.Control type='text' name="alphnumericid" placeholder='(8 digit alpha numeric ID generated by system)' />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={4}>
              <Form.Group>
                <Form.Label className='fw-bold mb-3'>JD number </Form.Label>
                <Form.Control type="text" defaultValue="1" />
              </Form.Group>
            </Col>
            <Col xs={4}>
              <Form.Group>
                <Form.Label className='fw-bold mb-3'>Client name </Form.Label>
                <Form.Control type="text" defaultValue="Pkrs" />
              </Form.Group>
            </Col>
            <Col xs={4}>
              <Form.Group>
                <Form.Label className='fw-bold mb-3'>JD title  </Form.Label>
                <Form.Control type="text" defaultValue="testing" />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={4}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3'>JD location </Form.Label>
                <Form.Control type="text" defaultValue="India" />
              </Form.Group>
            </Col>
           
            <Col xs={4}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold mb-3'>Candidate name  </Form.Label>
                <Form.Control type="text" defaultValue="Prashant Kumar" />
              </Form.Group>
            </Col>
          </Row>
          <Row>
            <Col xs={6}>
              <Form.Group className='mt-3'>
                <Form.Label className='fw-bold'>Date and Time of adding a candidate</Form.Label>
                <div className='d-flex'>
                  <Row>
                    <Col xs={6}>
                    <Form.Label className='fw-bold'>From</Form.Label>
                    <Form.Control type="date" />

                    </Col>
                    <Col xs={6}>
                    <Form.Label className='fw-bold'>To</Form.Label>
                    <Form.Control type="date" />

                    </Col>
                  </Row>
                </div>
              </Form.Group>
            </Col>
          </Row>
         

        </Form>
        </Container>
        </div>
        <div className='d-flex justify-content-center title-absolute py-4 border-top'>
                        <Button variant='secondary' className='mx-3 text-white'>Reset</Button>
                        <Link to='/ListOfCandidate'><Button variant='primary' className='mx-3 text-white'>Search</Button></Link>
                        <Link to='/ListOfCandidate'><Button variant='danger' className='mx-3 text-white'>Colse</Button></Link>
                    </div>
    </div>
  )
}

export default FilterStudent